### ISSUE TITLE
Multiple session/cookies for user on many user agent browser

### ISSUE THREAD

**Issue by emiliosa** [koseven/koseven#363] opened 2019-06-15 18:09 UTC
Hi everyone, im not sure if this is a bug, issue, or is a common behaviour.
Im still using kohana v3, auth/orm/many others modules.
Everything works fine since 4~5 years ago, but i always have the same issue:
After any user logs in, it gets redirect to home page. Later if i change the broswer mobile view, and useragent attr changes (some browser do not change like firefox, but chrome does), a new session is created and user gots redirect to login page: 

**Auth::instance()->logged_in()** is FALSE
**Auth::instance()->get_user()** is NULL

My config:
Im using database driver **Session::$default = 'database'**

Anyone with same problem?
Thanks.

**Comment by jstrobel** [comment] 2019-06-19 15:12
Hi @emiliosa - I am not sure if i get the problem right, what do you mean with:
> change the broswer mobile view
What do you change in detail?
Ev. you can check at the _read-function:
https://github.com/kohana/core/blob/bdbe81afb5a09cee4269d2e2210a0d293265231a/classes/Kohana/Session/Native.php#L25
Which does session-cookie-params. Eventual you have something which forces the recreate.

**Comment by emiliosa** [comment] 2019-06-21 20:12
Lets start from begin:
Im using database driver config, session is based on cookie (**name** attr).
After user logs in (using Chrome), a cookie session is created based on **agentUser** (you can see [here](https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Cookie.php#L153))

On desktop mode:

![image](https://user-images.githubusercontent.com/7193597/59947996-2a9b8400-9445-11e9-8bad-f2e37a21d827.png)

Switch to mobile view mode (from DevTools button):

![image](https://user-images.githubusercontent.com/7193597/59948032-4acb4300-9445-11e9-9eac-d78e07126ee9.png)

You can see **UserAgent** have been changed, user session that were based on this cookie is not the same and the user gets kickoff (**Auth::instance()->get_user()** is NULL).

This behaviour does not happen using Firefox.

Possible solutions:
1. Change salt method and stop using HTTP_AGENT_USER, but this could make user session more insecure.
2. Find a way to "auto-login" user with previous valid session?
3. Spoofing cookie?

I hope i made myself clear.
Thanks!

**Comment by toitzi** [comment] 2019-06-22 18:49
I'll have a look at it tomorrow, may be a bug...

**Comment by jstrobel** [comment] 2019-06-22 19:08
No i don‘t think that.
Like @emiliosa mentionedthere is a user agent check in the session class. and it changes in his case.
will have a look if my app has the same behavoir theae days

**Comment by toitzi** [comment] 2019-08-04 17:25
@emiliosa and @jstrobel  Sorry for my late reply...
After a bit research in this topic, it became clear.....no matter which driver you use for sessions they get stored in a Cookie. The cookie get's salted with:

Salt in bootsrap
Name
Value
**User-Agent**

Cookie Class Line [123](https://github.com/koseven/koseven/blob/61f40c4f73d8da5bd93ffa28fa2a690854136bbc/system/classes/KO7/Cookie.php#L123)
`return hash_hmac('sha1', $agent.$name.$value.Cookie::$salt, Cookie::$salt);`

Whenever you reload the browser / the user agent changes the cookie cannot be found and a new session is generated / the old one is no longer valid.

This is expected behavior BUT as of now i think we should change that.
There can be many reasons a user Agent changes:

Chrome Dev Tools (Your case)
Browser Extensions (Against tracking etc,..)
Browser Updates (Which - most of the time - happen automatically)
...

Every time something above happens the user will get logged out / the cookie will be invalid.
Since adding the User-Agent does not add an extra layer of security (If someone is able to steel your session...they most likely now your UA or have a way to find out / try out), i think we should remove it from the cookie generation.

What do you think @neo22s @jstrobel @svenbw @piotrbaczek

**Comment by toitzi** [comment] 2019-08-04 17:28
It's probably what @emiliosa said [here](https://github.com/koseven/koseven/issues/363#issuecomment-504558295) ..... 😅

**Comment by toitzi** [comment] 2020-01-17 08:01
Merged, will be within the release of 4.0

**Closed by toitzi** 2020-01-17 08:01 UTC
Labels: enhancement, help wanted
