### ISSUE TITLE
Defining your preferred language

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#121] opened 2017-07-05 17:35 UTC
To determine the most preferred language, [this function](https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/HTTP/Header.php#L827) is used, however it does not work correctly in this case:

For the test is used smartphone Samsung - Galaxy A5 with Russian language enabled, PHP 5.6.30

Test 1:
`HTTP::request_headers()->preferred_language(['en', 'ru',]);`

Test 2:
`locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE'])`

![screenshot 2017-07-05 003](https://user-images.githubusercontent.com/16259603/27873916-62e28188-61b6-11e7-882c-f41891b1f1bf.png)

As you can see, tests show that the language was incorrectly defined in both cases, but why? Samsung devices send the header in the wrong format? Even if it is, we need to fix this, given that the built-in PHP function also defines the wrong language?

**Comment by neo22s** [comment] 2017-09-02 16:39
can you do a PR with a fix? thanks

**Comment by errotan** [comment] 2017-09-03 11:42
I think the problem is that @knbv 's phone sends the languages with the same 'priority'. For example using this test controller action:

`$this->response->body(HTTP::request_headers()->preferred_language(['en', 'ru', 'hu']));`

Most browsers send the above like header. The 'en' has 0.3 and 'hu' has 0.8 which makes 'hu' greater and that is displayed.

Accept-Language: hu-HU,hu;q=0.8,en-US;q=0.5,en;q=0.3

Using the above the displayed value is 'en'

Accept-Language: hu-HU,hu,en-US,en

I think this is a correct behaviour because the script can choose any, but can do a PR to use the order specified by the browser. Should I do it?

**Comment by satanch** [comment] 2017-09-04 11:57
According to RFC 2616

>    The language quality factor assigned to a language-tag by the
>    Accept-Language field is the quality value of the longest language-
>    range in the field that matches the language-tag. If no language-
>    range in the field matches the tag, the language quality factor
>    assigned is 0. If no Accept-Language header is present in the
>    request, the server

**Comment by errotan** [comment] 2017-09-05 21:40
Made a PR for this: #151

**Comment by errotan** [comment] 2017-09-06 05:35
I need to fix the code to make the unit tests pass.

**Comment by errotan** [comment] 2017-09-08 19:07
Made a PR again which less modifies the original code and passes unit tests. Please review: #157

**Comment by piotrgolasz** [comment] 2017-09-21 15:09
@knbv Can you check the solution?

**Comment by knbv** [comment] 2017-09-21 22:38
@piotrgolasz, @errotan It is checked, now the language is determined correctly, thanks!

**Comment by knbv** [comment] 2017-10-01 18:51
@errotan, Your PR did not accept, can you send PR with corrections, or leave your comments on this?

**Comment by errotan** [comment] 2017-10-01 20:32
@knbv I forgot about the PR and rebased my repo from upstream which auto closed the PR. My PR was correct. Tried to recover from git objects but seems like it is lost :(

**Comment by errotan** [comment] 2017-10-01 21:13
@knbv Managed to restore the changes from .git/logs/HEAD doing PR again tomorrow morning.

**Comment by knbv** [comment] 2017-10-01 22:01
@errotan, Thank you! Please, pay attention to my remarks about the strict comparison.

Also, I have a saved solution if you can not restore the repository.

**Comment by piotrgolasz** [comment] 2017-12-02 22:53
Merged. Thank you @errotan

**Closed by piotrgolasz** 2017-12-02 22:53 UTC
