### ISSUE TITLE
PHP 7.1: Deprecated Mcrypt

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#14] opened 2017-01-11 19:51 UTC
https://github.com/kohana/core/issues/686
https://github.com/yclas/yclas/issues/2176

**Comment by piotrgolasz** [comment] 2017-01-24 21:32
I think here we need to keep current mcrypt but deprecate it, so that people can decode their data (but using raises warnings), and new functionality based on defuse or phpseclib.

**Comment by jstrobel** [comment] 2017-01-24 22:48
What do you think about the dependency on libs (defuse,phpseclib) for that function instead of openssl? Tending to a no or less-dependency if it save

**Comment by neo22s** [comment] 2017-01-25 06:24
I need to do research no clue about this xD

**Comment by svenbw** [comment] 2017-01-25 07:52
What about using the same idea as the database module? Make a module for encrypt one that is backward compatible with the current version.
There can be different instances, default is the same as the current mcrypt, additional instances  can be created using another algorithm, which can be used for making auth stuff safe.
It would require more work but has some options (like writing your own driver based on a library or openssl)

**Comment by neo22s** [comment] 2017-01-25 08:55
sounds good to me!

**Comment by svenbw** [comment] 2017-01-27 20:05
I finished most of the code and all encrypt Kohana unit tests without a problem. I will list my changes and concept below before committing the code to the repo.

I moved the `Encrypt.php` files from the Kohana core to the encrypt module directory, leaving the original test in Kohana itself (as a test for backward compatibility).

The Encrypt class is now a more or less "empty" wrapper that creates an _encryption engine_ instance. There are two engines the original mcrypt engine that is loaded by default. The second engine is based on openssl.

`encode` en `decode` call the abstract `encrypt` and `decrypt` functions of the encrypt engine class. It is now possible to create an instance with a configuration array (or with the original string arguments).

`new Encrypt` will create a new encryption class using the mcrypt engine like it always had.
In the config file one _can_ add a new key for `'type'`, assigning this to `'mcrypt'` will start the mcrypt engine, `'openssl'` an openssl engine.

It is possible to create different encrypt instances with different encryption engines in the config file.

The _create_iv function is still in place to keep the original test working. I had to remove the tests on the properties (`assertSameProtectedProperty`) for the `_key`, `_cipher` and `_mode` properties because they where moved to the engine class.

**Comment by piotrgolasz** [comment] 2017-01-27 20:37
Gentlemen, the problem is not mere encoding the information, but also signing the encrypted code so that if the data have been modified, we can reject them and straight output false. So beside swapping to openssl there is also a need to hmac_sign() the data.

**Comment by svenbw** [comment] 2017-01-27 20:41
@piotrgolasz The openssl engine is based on the code above.

**Comment by svenbw** [comment] 2017-01-29 10:45
I added the the encrypt module to my own repo. There are [quite some differences](https://github.com/svenbw/koseven/commit/213843a02ed23b5ee990bdd9ad69a6a120ce8a79?diff=unified).
Since it's a module it needs to be added to the bootstrap module list if one wants to support encryption on the sessions.

**Comment by roman-huliak** [comment] 2017-01-29 10:57
Will it works on php5? Only mcrypt or ssl also?

**Comment by svenbw** [comment] 2017-01-29 11:00
Both _should_ work, although I did not test all configurations (yet). For php5 there is no `random_bytes` call so there the iv is created using the `mcrypt_create_iv` call.

**Comment by roman-huliak** [comment] 2017-01-29 11:10
Error on L180 

https://github.com/svenbw/koseven/blob/master/modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php

$$this

**Comment by svenbw** [comment] 2017-01-29 11:15
@roman-huliak thanks. Manual merging... never a good idea. I will fix it.

**Comment by roman-huliak** [comment] 2017-01-29 12:21
Unit tests not passing for fatal error
EncryptTest->test_key_normalization()

Call to undefined method EncryptTest_KeyNormalized::_normalize_key()

For me is solution delete test or mark as skipped.

**Comment by neo22s** [comment] 2017-01-30 19:58
Hello! I am not sure if we should worry much about php5, its close to the end... 5.6 will only include bug fixes and the point of koseven is that is compatible with PHP7 xD 

Not sure what you all think, I will ask now. But I will not test on PHP 5 at all. xD

**Comment by svenbw** [comment] 2017-01-30 20:02
I think it's nice if you could drop in a new version of Koseven in an older php version (depends on what the host offers)... And the code is there.
My tests passed because I used an old version of php to run the unit tests for 5.x
I will fix the unit tests.

**Comment by roman-huliak** [comment] 2017-02-16 13:29
In install.php in root mcrypt is there as optional extension. 
Can be removed. Or changed to detect openssl.

**Comment by jstrobel** [comment] 2017-02-21 14:06
Just for info: there is a RFC which has been accepted to become core in 7.2.:
https://wiki.php.net/rfc/libsodium

**Comment by piotrgolasz** [comment] 2017-03-08 17:58
Ok so for PHP 7,2 we will have libsodium, for PHP 7.1 we have AEAD mode of openssl_encrypt otherwise we have to use openssl_encrypt with AES-256-CTR and custom authentication.

**Comment by piotrgolasz** [comment] 2017-03-21 09:14
@svenbw Why weren't your changes merged?

**Comment by svenbw** [comment] 2017-03-21 21:39
@piotrgolasz Not yet, someone should do some testing on it before we merge them. I have the modifications on a separate branch in my fork, but I need to sync them before creating a new PR.

**Comment by roman-huliak** [comment] 2017-03-22 06:47
I am using this modification (mcrypt->openssl) more than  3 weeks on production server. all is OK.

**Comment by piotrgolasz** [comment] 2017-03-22 12:51
@svenbw that's what unittests are for ;)

**Comment by svenbw** [comment] 2017-03-24 23:07
Finally created the PR for this issue

**Comment by neo22s** [comment] 2017-03-31 05:43
closed at https://github.com/koseven/koseven/pull/73

**Comment by piotrgolasz** [comment] 2017-03-31 13:32
I'll reopen this just for simple question: Why is Engine Openssl defaulting to mcrypt? https://github.com/koseven/koseven/blob/devel/modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php#L210

**Comment by svenbw** [comment] 2017-03-31 13:41
Because `random_bytes` is only available in PHP version 7 and is used if the function is available.
If it is **NOT** available mcrypt_create_iv is used to create the key. This allows the creation of a random_byte array in older PHP versions (which are still supported, hence the version check).

**Closed** 2017-03-31 18:26 UTC
Labels: bug, enhancement
